[2024-06-07T10:35:38.367+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_taskflow_with_kafka.fetch_and_publish_to_kafka manual__2024-06-07T10:35:36.940473+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
