[2024-06-17T10:50:12.270+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T10:50:12.287+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.wait_for_publish_dag manual__2024-06-17T10:50:11.070570+00:00 [queued]>
[2024-06-17T10:50:12.293+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.wait_for_publish_dag manual__2024-06-17T10:50:11.070570+00:00 [queued]>
[2024-06-17T10:50:12.293+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-17T10:50:12.303+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_publish_dag> on 2024-06-17 10:50:11.070570+00:00
[2024-06-17T10:50:12.308+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1255) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-17T10:50:12.309+0000] {standard_task_runner.py:63} INFO - Started process 1268 to run task
[2024-06-17T10:50:12.309+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_kafka_consumeAndLoad', 'wait_for_publish_dag', 'manual__2024-06-17T10:50:11.070570+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/ergast_kafka_consume_and_load.py', '--cfg-path', '/tmp/tmpmp1yweb2']
[2024-06-17T10:50:12.311+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask wait_for_publish_dag
[2024-06-17T10:50:12.346+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.wait_for_publish_dag manual__2024-06-17T10:50:11.070570+00:00 [running]> on host 688ecc0cce5b
[2024-06-17T10:50:12.407+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_kafka_consumeAndLoad' AIRFLOW_CTX_TASK_ID='wait_for_publish_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T10:50:11.070570+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T10:50:11.070570+00:00'
[2024-06-17T10:50:12.407+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T10:50:12.408+0000] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-17T10:50:12.408+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:50:12.408+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-17T10:50:42.414+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:51:12.421+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:51:42.428+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:52:12.434+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:52:42.442+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:53:12.452+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:53:42.459+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:54:12.467+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:54:42.477+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:55:12.483+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:55:42.494+0000] {external_task.py:258} INFO - Poking for tasks ['fetch_and_publish_laps'] in dag f1_data_pipeline_kafka_fetchAndPublish on 2024-06-17T10:50:11.070570+00:00 ... 
[2024-06-17T10:56:10.644+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-06-17T10:56:10.645+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-17T10:56:10.645+0000] {process_utils.py:132} INFO - Sending 15 to group 1268. PIDs of all processes in the group: [1268]
[2024-06-17T10:56:10.645+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 1268
[2024-06-17T10:56:10.646+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-17T10:56:10.646+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T10:56:10.651+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 292, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-17T10:56:10.655+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_kafka_consumeAndLoad, task_id=wait_for_publish_dag, run_id=manual__2024-06-17T10:50:11.070570+00:00, execution_date=20240617T105011, start_date=20240617T105012, end_date=20240617T105610
[2024-06-17T10:56:10.663+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task wait_for_publish_dag ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(f1_data_pipeline_kafka_consumeAndLoad, wait_for_publish_dag, manual__2024-06-17T10:50:11.070570+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'wait_for_publish_dag', 'dag_id': 'f1_data_pipeline_kafka_consumeAndLoad', 'run_id': 'manual__2024-06-17T10:50:11.070570+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 6, 17, 10, 50, 12, 287823, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 6, 17, 10, 56, 10, 654760, tzinfo=Timezone('UTC')), 'duration': 358}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 1268)
[2024-06-17T10:56:10.672+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=1268, status='terminated', exitcode=1, started='10:50:12') (1268) terminated with exit code 1
