[2024-06-12T10:46:21.414+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T10:46:21.427+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-12T10:46:19.778116+00:00 [queued]>
[2024-06-12T10:46:21.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-12T10:46:19.778116+00:00 [queued]>
[2024-06-12T10:46:21.431+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-12T10:46:21.439+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalTaskSensor): wait_for_elt_dag> on 2024-06-12 10:46:19.778116+00:00
[2024-06-12T10:46:21.444+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1041) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T10:46:21.445+0000] {standard_task_runner.py:63} INFO - Started process 1043 to run task
[2024-06-12T10:46:21.445+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow_with_kafka', 'wait_for_elt_dag', 'manual__2024-06-12T10:46:19.778116+00:00', '--job-id', '39', '--raw', '--subdir', 'DAGS_FOLDER/kafka_data_scrape.py', '--cfg-path', '/tmp/tmpdy0lbrv3']
[2024-06-12T10:46:21.446+0000] {standard_task_runner.py:91} INFO - Job 39: Subtask wait_for_elt_dag
[2024-06-12T10:46:21.478+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow_with_kafka.wait_for_elt_dag manual__2024-06-12T10:46:19.778116+00:00 [running]> on host 52285cb34a44
[2024-06-12T10:46:21.535+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow_with_kafka' AIRFLOW_CTX_TASK_ID='wait_for_elt_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T10:46:19.778116+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T10:46:19.778116+00:00'
[2024-06-12T10:46:21.536+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T10:46:21.536+0000] {baseoperator.py:399} WARNING - ExternalTaskSensor.execute cannot be called outside TaskInstance!
[2024-06-12T10:46:21.536+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:46:21.537+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/utils/session.py:79: DeprecationWarning: This method is deprecated and will be removed in future.
  return func(*args, session=session, **kwargs)

[2024-06-12T10:47:21.543+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:48:21.551+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:49:21.559+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:50:21.568+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:51:21.579+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:52:21.589+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:53:21.596+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:54:21.607+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:55:21.619+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:56:21.627+0000] {external_task.py:258} INFO - Poking for tasks ['load_raceResults_task'] in dag f1_data_pipeline_taskflow on 2024-06-12T10:46:19.778116+00:00 ... 
[2024-06-12T10:56:21.638+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T10:56:21.639+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/external_task.py", line 348, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 281, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 600.1020663489999 seconds exceeds the specified timeout of 600.0.
[2024-06-12T10:56:21.648+0000] {taskinstance.py:1206} INFO - Immediate failure requested. Marking task as FAILED. dag_id=f1_data_pipeline_taskflow_with_kafka, task_id=wait_for_elt_dag, run_id=manual__2024-06-12T10:46:19.778116+00:00, execution_date=20240612T104619, start_date=20240612T104621, end_date=20240612T105621
[2024-06-12T10:56:21.658+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 39 for task wait_for_elt_dag (Sensor has timed out; run duration of 600.1020663489999 seconds exceeds the specified timeout of 600.0.; 1043)
[2024-06-12T10:56:21.665+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T10:56:21.676+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T10:56:21.678+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
