[2024-06-14T12:35:47.622+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T12:35:47.637+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.consume_and_load_lapsDim manual__2024-06-14T12:35:24.060229+00:00 [queued]>
[2024-06-14T12:35:47.643+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.consume_and_load_lapsDim manual__2024-06-14T12:35:24.060229+00:00 [queued]>
[2024-06-14T12:35:47.643+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T12:35:47.652+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): consume_and_load_lapsDim> on 2024-06-14 12:35:24.060229+00:00
[2024-06-14T12:35:47.657+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2659) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-14T12:35:47.659+0000] {standard_task_runner.py:63} INFO - Started process 2665 to run task
[2024-06-14T12:35:47.659+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_kafka_consumeAndLoad', 'consume_and_load_lapsDim', 'manual__2024-06-14T12:35:24.060229+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/ergast_kafka_consume_and_load.py', '--cfg-path', '/tmp/tmpe7nntmuu']
[2024-06-14T12:35:47.661+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask consume_and_load_lapsDim
[2024-06-14T12:35:47.698+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_kafka_consumeAndLoad.consume_and_load_lapsDim manual__2024-06-14T12:35:24.060229+00:00 [running]> on host e4ecbb11494f
[2024-06-14T12:35:47.762+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_kafka_consumeAndLoad' AIRFLOW_CTX_TASK_ID='consume_and_load_lapsDim' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T12:35:24.060229+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T12:35:24.060229+00:00'
[2024-06-14T12:35:47.763+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T12:35:47.765+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.144.6', 9092)]>: connecting to kafka:9092 [('192.168.144.6', 9092) IPv4]
[2024-06-14T12:35:47.766+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-06-14T12:35:47.766+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('192.168.144.6', 9092)]>: Connection complete.
[2024-06-14T12:35:47.868+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-06-14T12:35:47.869+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-06-14T12:35:47.870+0000] {consumer.py:122} WARNING - group_id is None: disabling auto-commit.
[2024-06-14T12:35:47.870+0000] {subscription_state.py:167} INFO - Updating subscribed topics to: ('f1_data_topic_laps',)
[2024-06-14T12:35:47.871+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-14T12:35:47.872+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-06-14T12:35:47.911+0000] {subscription_state.py:253} INFO - Updated partition assignment: [('f1_data_topic_laps', 0)]
[2024-06-14T12:35:47.912+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.144.6', 9092)]>: connecting to kafka:9092 [('192.168.144.6', 9092) IPv4]
[2024-06-14T12:35:47.912+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('192.168.144.6', 9092)]>: Connection complete.
[2024-06-14T12:35:47.912+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('192.168.144.6', 9092)]>: Closing connection. 
[2024-06-14T12:37:33.568+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-06-14T12:37:33.569+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-14T12:37:33.569+0000] {process_utils.py:132} INFO - Sending 15 to group 2665. PIDs of all processes in the group: [2665]
[2024-06-14T12:37:33.569+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 2665
[2024-06-14T12:37:33.571+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-14T12:37:33.572+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T12:37:33.578+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ergast_kafka_consume_and_load.py", line 517, in consume_and_load_lapsDim
    lap_check_result = session.execute(lap_check_query).fetchone()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1717, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2138, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.12/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2024-06-14T12:37:33.586+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_kafka_consumeAndLoad, task_id=consume_and_load_lapsDim, run_id=manual__2024-06-14T12:35:24.060229+00:00, execution_date=20240614T123524, start_date=20240614T123547, end_date=20240614T123733
[2024-06-14T12:37:33.594+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task consume_and_load_lapsDim ((psycopg2.errors.ForeignKeyViolation) insert or update on table "task_fail" violates foreign key constraint "task_fail_ti_fkey"
DETAIL:  Key (dag_id, task_id, run_id, map_index)=(f1_data_pipeline_kafka_consumeAndLoad, consume_and_load_lapsDim, manual__2024-06-14T12:35:24.060229+00:00, -1) is not present in table "task_instance".

[SQL: INSERT INTO task_fail (task_id, dag_id, run_id, map_index, start_date, end_date, duration) VALUES (%(task_id)s, %(dag_id)s, %(run_id)s, %(map_index)s, %(start_date)s, %(end_date)s, %(duration)s) RETURNING task_fail.id]
[parameters: {'task_id': 'consume_and_load_lapsDim', 'dag_id': 'f1_data_pipeline_kafka_consumeAndLoad', 'run_id': 'manual__2024-06-14T12:35:24.060229+00:00', 'map_index': -1, 'start_date': datetime.datetime(2024, 6, 14, 12, 35, 47, 637990, tzinfo=Timezone('UTC')), 'end_date': datetime.datetime(2024, 6, 14, 12, 37, 33, 585699, tzinfo=Timezone('UTC')), 'duration': 105}]
(Background on this error at: https://sqlalche.me/e/14/gkpj); 2665)
[2024-06-14T12:37:33.622+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=2665, status='terminated', exitcode=1, started='12:35:46') (2665) terminated with exit code 1
