[2024-05-31T13:31:00.177+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T13:31:00.192+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:31:00.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:31:00.196+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T13:31:00.204+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T13:31:00.208+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=263) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T13:31:00.209+0000] {standard_task_runner.py:63} INFO - Started process 265 to run task
[2024-05-31T13:31:00.209+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpvwip8nps']
[2024-05-31T13:31:00.210+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_data__4
[2024-05-31T13:31:00.241+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 71bdf4d24007
[2024-05-31T13:31:00.340+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T13:31:00.341+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T13:31:00.342+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T13:31:00.342+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T13:31:00.362+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T13:31:00.362+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T13:31:00.369+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T133100, end_date=20240531T133100
[2024-05-31T13:31:00.382+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T13:31:00.393+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T13:31:00.394+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T13:38:35.841+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T13:38:35.855+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:38:35.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:38:35.861+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T13:38:35.869+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T13:38:35.873+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T13:38:35.874+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2024-05-31T13:38:35.874+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpcv2fo6uy']
[2024-05-31T13:38:35.876+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_data__4
[2024-05-31T13:38:35.906+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 140bbde645f4
[2024-05-31T13:38:36.017+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T13:38:36.018+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T13:38:36.019+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T13:38:36.019+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T13:38:36.035+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T13:38:36.035+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.DatatypeMismatch: column "time" is of type time without time zone but expression is of type numeric
LINE 1: ...862, 17.0, 1, 'Chinese Grand Prix', '2012-04-15', 20.626, 20...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 122, in load_data
    df.to_sql(table_name, engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "time" is of type time without time zone but expression is of type numeric
LINE 1: ...862, 17.0, 1, 'Chinese Grand Prix', '2012-04-15', 20.626, 20...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO "raceDim" ("raceId", "circuitId", "statusId", name_x, date, time, year, round, url_x) VALUES (%(raceId)s, %(circuitId)s, %(statusId)s, %(name_x)s, %(date)s, %(time)s, %(year)s, %(round)s, %(url_x)s)]
[parameters: ({'raceId': 860, 'circuitId': 1.0, 'statusId': 1, 'name_x': 'Australian Grand Prix', 'date': '2012-03-18', 'time': None, 'year': 2012, 'round': 1, 'url_x': 'http://en.wikipedia.org/wiki/2012_Australian_Grand_Prix'}, {'raceId': 861, 'circuitId': 2.0, 'statusId': 1, 'name_x': 'Malaysian Grand Prix', 'date': '2012-03-25', 'time': None, 'year': 2012, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2012_Malaysian_Grand_Prix'}, {'raceId': 862, 'circuitId': 17.0, 'statusId': 1, 'name_x': 'Chinese Grand Prix', 'date': '2012-04-15', 'time': 20.626, 'year': 2012, 'round': 3, 'url_x': 'http://en.wikipedia.org/wiki/2012_Chinese_Grand_Prix'}, {'raceId': 863, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2012-04-22', 'time': 58.984, 'year': 2012, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2012_Bahrain_Grand_Prix'}, {'raceId': 864, 'circuitId': 4.0, 'statusId': 1, 'name_x': 'Spanish Grand Prix', 'date': '2012-05-13', 'time': None, 'year': 2012, 'round': 5, 'url_x': 'http://en.wikipedia.org/wiki/2012_Spanish_Grand_Prix'}, {'raceId': 865, 'circuitId': 6.0, 'statusId': 1, 'name_x': 'Monaco Grand Prix', 'date': '2012-05-27', 'time': 4.101, 'year': 2012, 'round': 6, 'url_x': 'http://en.wikipedia.org/wiki/2012_Monaco_Grand_Prix'}, {'raceId': 866, 'circuitId': 7.0, 'statusId': 1, 'name_x': 'Canadian Grand Prix', 'date': '2012-06-10', 'time': None, 'year': 2012, 'round': 7, 'url_x': 'http://en.wikipedia.org/wiki/2012_Canadian_Grand_Prix'}, {'raceId': 867, 'circuitId': 12.0, 'statusId': 1, 'name_x': 'European Grand Prix', 'date': '2012-06-24', 'time': 24.653, 'year': 2012, 'round': 8, 'url_x': 'http://en.wikipedia.org/wiki/2012_European_Grand_Prix'}  ... displaying 10 of 232 total bound parameter sets ...  {'raceId': 990, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2018-04-08', 'time': None, 'year': 2018, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2018_Bahrain_Grand_Prix'}, {'raceId': 951, 'circuitId': 71.0, 'statusId': 1, 'name_x': 'Russian Grand Prix', 'date': '2016-05-01', 'time': 31.998, 'year': 2016, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2016_Russian_Grand_Prix'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-05-31T13:38:36.046+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T133835, end_date=20240531T133836
[2024-05-31T13:38:36.062+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task load_data__4 ((psycopg2.errors.DatatypeMismatch) column "time" is of type time without time zone but expression is of type numeric
LINE 1: ...862, 17.0, 1, 'Chinese Grand Prix', '2012-04-15', 20.626, 20...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO "raceDim" ("raceId", "circuitId", "statusId", name_x, date, time, year, round, url_x) VALUES (%(raceId)s, %(circuitId)s, %(statusId)s, %(name_x)s, %(date)s, %(time)s, %(year)s, %(round)s, %(url_x)s)]
[parameters: ({'raceId': 860, 'circuitId': 1.0, 'statusId': 1, 'name_x': 'Australian Grand Prix', 'date': '2012-03-18', 'time': None, 'year': 2012, 'round': 1, 'url_x': 'http://en.wikipedia.org/wiki/2012_Australian_Grand_Prix'}, {'raceId': 861, 'circuitId': 2.0, 'statusId': 1, 'name_x': 'Malaysian Grand Prix', 'date': '2012-03-25', 'time': None, 'year': 2012, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2012_Malaysian_Grand_Prix'}, {'raceId': 862, 'circuitId': 17.0, 'statusId': 1, 'name_x': 'Chinese Grand Prix', 'date': '2012-04-15', 'time': 20.626, 'year': 2012, 'round': 3, 'url_x': 'http://en.wikipedia.org/wiki/2012_Chinese_Grand_Prix'}, {'raceId': 863, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2012-04-22', 'time': 58.984, 'year': 2012, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2012_Bahrain_Grand_Prix'}, {'raceId': 864, 'circuitId': 4.0, 'statusId': 1, 'name_x': 'Spanish Grand Prix', 'date': '2012-05-13', 'time': None, 'year': 2012, 'round': 5, 'url_x': 'http://en.wikipedia.org/wiki/2012_Spanish_Grand_Prix'}, {'raceId': 865, 'circuitId': 6.0, 'statusId': 1, 'name_x': 'Monaco Grand Prix', 'date': '2012-05-27', 'time': 4.101, 'year': 2012, 'round': 6, 'url_x': 'http://en.wikipedia.org/wiki/2012_Monaco_Grand_Prix'}, {'raceId': 866, 'circuitId': 7.0, 'statusId': 1, 'name_x': 'Canadian Grand Prix', 'date': '2012-06-10', 'time': None, 'year': 2012, 'round': 7, 'url_x': 'http://en.wikipedia.org/wiki/2012_Canadian_Grand_Prix'}, {'raceId': 867, 'circuitId': 12.0, 'statusId': 1, 'name_x': 'European Grand Prix', 'date': '2012-06-24', 'time': 24.653, 'year': 2012, 'round': 8, 'url_x': 'http://en.wikipedia.org/wiki/2012_European_Grand_Prix'}  ... displaying 10 of 232 total bound parameter sets ...  {'raceId': 990, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2018-04-08', 'time': None, 'year': 2018, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2018_Bahrain_Grand_Prix'}, {'raceId': 951, 'circuitId': 71.0, 'statusId': 1, 'name_x': 'Russian Grand Prix', 'date': '2016-05-01', 'time': 31.998, 'year': 2016, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2016_Russian_Grand_Prix'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 263)
[2024-05-31T13:38:36.087+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-31T13:38:36.098+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T13:38:36.100+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T13:42:26.887+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T13:42:26.902+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:42:26.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:42:26.907+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T13:42:26.916+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T13:42:26.921+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=254) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T13:42:26.922+0000] {standard_task_runner.py:63} INFO - Started process 256 to run task
[2024-05-31T13:42:26.922+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmppue1ih27']
[2024-05-31T13:42:26.923+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_data__4
[2024-05-31T13:42:26.954+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 8abcc7a02d3d
[2024-05-31T13:42:27.057+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T13:42:27.057+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T13:42:27.058+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T13:42:27.059+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T13:42:27.067+0000] {warnings.py:110} WARNING - /opt/***/dags/etl_dag.py:123: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  df.to_sql(table_name, engine, if_exists='append', index=False)

[2024-05-31T13:42:27.075+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T13:42:27.076+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.DatatypeMismatch: column "time" is of type time without time zone but expression is of type bigint
LINE 1: ..., 1.0, 1, 'Australian Grand Prix', '2012-03-18',  -922337203...
                                                             ^
HINT:  You will need to rewrite or cast the expression.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 123, in load_data
    df.to_sql(table_name, engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DatatypeMismatch) column "time" is of type time without time zone but expression is of type bigint
LINE 1: ..., 1.0, 1, 'Australian Grand Prix', '2012-03-18',  -922337203...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO "raceDim" ("raceId", "circuitId", "statusId", name_x, date, time, year, round, url_x) VALUES (%(raceId)s, %(circuitId)s, %(statusId)s, %(name_x)s, %(date)s, %(time)s, %(year)s, %(round)s, %(url_x)s)]
[parameters: ({'raceId': 860, 'circuitId': 1.0, 'statusId': 1, 'name_x': 'Australian Grand Prix', 'date': '2012-03-18', 'time': -9223372036854775808, 'year': 2012, 'round': 1, 'url_x': 'http://en.wikipedia.org/wiki/2012_Australian_Grand_Prix'}, {'raceId': 861, 'circuitId': 2.0, 'statusId': 1, 'name_x': 'Malaysian Grand Prix', 'date': '2012-03-25', 'time': -9223372036854775808, 'year': 2012, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2012_Malaysian_Grand_Prix'}, {'raceId': 862, 'circuitId': 17.0, 'statusId': 1, 'name_x': 'Chinese Grand Prix', 'date': '2012-04-15', 'time': 20, 'year': 2012, 'round': 3, 'url_x': 'http://en.wikipedia.org/wiki/2012_Chinese_Grand_Prix'}, {'raceId': 863, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2012-04-22', 'time': 58, 'year': 2012, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2012_Bahrain_Grand_Prix'}, {'raceId': 864, 'circuitId': 4.0, 'statusId': 1, 'name_x': 'Spanish Grand Prix', 'date': '2012-05-13', 'time': -9223372036854775808, 'year': 2012, 'round': 5, 'url_x': 'http://en.wikipedia.org/wiki/2012_Spanish_Grand_Prix'}, {'raceId': 865, 'circuitId': 6.0, 'statusId': 1, 'name_x': 'Monaco Grand Prix', 'date': '2012-05-27', 'time': 4, 'year': 2012, 'round': 6, 'url_x': 'http://en.wikipedia.org/wiki/2012_Monaco_Grand_Prix'}, {'raceId': 866, 'circuitId': 7.0, 'statusId': 1, 'name_x': 'Canadian Grand Prix', 'date': '2012-06-10', 'time': -9223372036854775808, 'year': 2012, 'round': 7, 'url_x': 'http://en.wikipedia.org/wiki/2012_Canadian_Grand_Prix'}, {'raceId': 867, 'circuitId': 12.0, 'statusId': 1, 'name_x': 'European Grand Prix', 'date': '2012-06-24', 'time': 24, 'year': 2012, 'round': 8, 'url_x': 'http://en.wikipedia.org/wiki/2012_European_Grand_Prix'}  ... displaying 10 of 232 total bound parameter sets ...  {'raceId': 990, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2018-04-08', 'time': -9223372036854775808, 'year': 2018, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2018_Bahrain_Grand_Prix'}, {'raceId': 951, 'circuitId': 71.0, 'statusId': 1, 'name_x': 'Russian Grand Prix', 'date': '2016-05-01', 'time': 31, 'year': 2016, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2016_Russian_Grand_Prix'})]
(Background on this error at: https://sqlalche.me/e/14/f405)
[2024-05-31T13:42:27.086+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T134226, end_date=20240531T134227
[2024-05-31T13:42:27.095+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task load_data__4 ((psycopg2.errors.DatatypeMismatch) column "time" is of type time without time zone but expression is of type bigint
LINE 1: ..., 1.0, 1, 'Australian Grand Prix', '2012-03-18',  -922337203...
                                                             ^
HINT:  You will need to rewrite or cast the expression.

[SQL: INSERT INTO "raceDim" ("raceId", "circuitId", "statusId", name_x, date, time, year, round, url_x) VALUES (%(raceId)s, %(circuitId)s, %(statusId)s, %(name_x)s, %(date)s, %(time)s, %(year)s, %(round)s, %(url_x)s)]
[parameters: ({'raceId': 860, 'circuitId': 1.0, 'statusId': 1, 'name_x': 'Australian Grand Prix', 'date': '2012-03-18', 'time': -9223372036854775808, 'year': 2012, 'round': 1, 'url_x': 'http://en.wikipedia.org/wiki/2012_Australian_Grand_Prix'}, {'raceId': 861, 'circuitId': 2.0, 'statusId': 1, 'name_x': 'Malaysian Grand Prix', 'date': '2012-03-25', 'time': -9223372036854775808, 'year': 2012, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2012_Malaysian_Grand_Prix'}, {'raceId': 862, 'circuitId': 17.0, 'statusId': 1, 'name_x': 'Chinese Grand Prix', 'date': '2012-04-15', 'time': 20, 'year': 2012, 'round': 3, 'url_x': 'http://en.wikipedia.org/wiki/2012_Chinese_Grand_Prix'}, {'raceId': 863, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2012-04-22', 'time': 58, 'year': 2012, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2012_Bahrain_Grand_Prix'}, {'raceId': 864, 'circuitId': 4.0, 'statusId': 1, 'name_x': 'Spanish Grand Prix', 'date': '2012-05-13', 'time': -9223372036854775808, 'year': 2012, 'round': 5, 'url_x': 'http://en.wikipedia.org/wiki/2012_Spanish_Grand_Prix'}, {'raceId': 865, 'circuitId': 6.0, 'statusId': 1, 'name_x': 'Monaco Grand Prix', 'date': '2012-05-27', 'time': 4, 'year': 2012, 'round': 6, 'url_x': 'http://en.wikipedia.org/wiki/2012_Monaco_Grand_Prix'}, {'raceId': 866, 'circuitId': 7.0, 'statusId': 1, 'name_x': 'Canadian Grand Prix', 'date': '2012-06-10', 'time': -9223372036854775808, 'year': 2012, 'round': 7, 'url_x': 'http://en.wikipedia.org/wiki/2012_Canadian_Grand_Prix'}, {'raceId': 867, 'circuitId': 12.0, 'statusId': 1, 'name_x': 'European Grand Prix', 'date': '2012-06-24', 'time': 24, 'year': 2012, 'round': 8, 'url_x': 'http://en.wikipedia.org/wiki/2012_European_Grand_Prix'}  ... displaying 10 of 232 total bound parameter sets ...  {'raceId': 990, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2018-04-08', 'time': -9223372036854775808, 'year': 2018, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2018_Bahrain_Grand_Prix'}, {'raceId': 951, 'circuitId': 71.0, 'statusId': 1, 'name_x': 'Russian Grand Prix', 'date': '2016-05-01', 'time': 31, 'year': 2016, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2016_Russian_Grand_Prix'})]
(Background on this error at: https://sqlalche.me/e/14/f405); 256)
[2024-05-31T13:42:27.135+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-31T13:42:27.146+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T13:42:27.147+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T13:46:06.093+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T13:46:06.114+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:46:06.119+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:46:06.119+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T13:46:06.128+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T13:46:06.132+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T13:46:06.133+0000] {standard_task_runner.py:63} INFO - Started process 263 to run task
[2024-05-31T13:46:06.134+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp50odvsfa']
[2024-05-31T13:46:06.135+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_data__4
[2024-05-31T13:46:06.169+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 2605f7bd5eb2
[2024-05-31T13:46:06.306+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T13:46:06.307+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T13:46:06.308+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T13:46:06.308+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T13:46:06.326+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T13:46:06.326+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T13:46:06.332+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T134606, end_date=20240531T134606
[2024-05-31T13:46:06.346+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T13:46:06.356+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T13:46:06.357+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T13:52:43.426+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T13:52:43.442+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:52:43.448+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:52:43.449+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T13:52:43.457+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T13:52:43.462+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=259) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T13:52:43.463+0000] {standard_task_runner.py:63} INFO - Started process 261 to run task
[2024-05-31T13:52:43.463+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpwmmv54f7']
[2024-05-31T13:52:43.464+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask load_data__4
[2024-05-31T13:52:43.497+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host a95aa6127783
[2024-05-31T13:52:43.616+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T13:52:43.617+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T13:52:43.618+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T13:52:43.619+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T13:52:43.638+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T13:52:43.638+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type time: "+1:19.719"
LINE 1: ...61, 2.0, 1, 'Malaysian Grand Prix', '2012-03-25', '+1:19.719...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 123, in load_data
    df.to_sql(table_name, engine, if_exists='append', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3008, in to_sql
    return sql.to_sql(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 788, in to_sql
    return pandas_sql.to_sql(
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1958, in to_sql
    total_inserted = sql_engine.insert_records(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1507, in insert_records
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1498, in insert_records
    return table.insert(chunksize=chunksize, method=method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 1059, in insert
    num_inserted = exec_insert(conn, keys, chunk_iter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/sql.py", line 951, in _execute_insert
    result = conn.execute(self.table.insert(), data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1890, in _execute_context
    self.dialect.do_executemany(
  File "/home/airflow/.local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 982, in do_executemany
    context._psycopg2_fetched_rows = xtras.execute_values(
                                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
sqlalchemy.exc.DataError: (psycopg2.errors.InvalidDatetimeFormat) invalid input syntax for type time: "+1:19.719"
LINE 1: ...61, 2.0, 1, 'Malaysian Grand Prix', '2012-03-25', '+1:19.719...
                                                             ^

[SQL: INSERT INTO "raceDim" ("raceId", "circuitId", "statusId", name_x, date, time, year, round, url_x) VALUES (%(raceId)s, %(circuitId)s, %(statusId)s, %(name_x)s, %(date)s, %(time)s, %(year)s, %(round)s, %(url_x)s)]
[parameters: ({'raceId': 860, 'circuitId': 1.0, 'statusId': 1, 'name_x': 'Australian Grand Prix', 'date': '2012-03-18', 'time': '1:34:09.565', 'year': 2012, 'round': 1, 'url_x': 'http://en.wikipedia.org/wiki/2012_Australian_Grand_Prix'}, {'raceId': 861, 'circuitId': 2.0, 'statusId': 1, 'name_x': 'Malaysian Grand Prix', 'date': '2012-03-25', 'time': '+1:19.719', 'year': 2012, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2012_Malaysian_Grand_Prix'}, {'raceId': 862, 'circuitId': 17.0, 'statusId': 1, 'name_x': 'Chinese Grand Prix', 'date': '2012-04-15', 'time': '+20.626', 'year': 2012, 'round': 3, 'url_x': 'http://en.wikipedia.org/wiki/2012_Chinese_Grand_Prix'}, {'raceId': 863, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2012-04-22', 'time': '+58.984', 'year': 2012, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2012_Bahrain_Grand_Prix'}, {'raceId': 864, 'circuitId': 4.0, 'statusId': 1, 'name_x': 'Spanish Grand Prix', 'date': '2012-05-13', 'time': '+1:25.246', 'year': 2012, 'round': 5, 'url_x': 'http://en.wikipedia.org/wiki/2012_Spanish_Grand_Prix'}, {'raceId': 865, 'circuitId': 6.0, 'statusId': 1, 'name_x': 'Monaco Grand Prix', 'date': '2012-05-27', 'time': '+4.101', 'year': 2012, 'round': 6, 'url_x': 'http://en.wikipedia.org/wiki/2012_Monaco_Grand_Prix'}, {'raceId': 866, 'circuitId': 7.0, 'statusId': 1, 'name_x': 'Canadian Grand Prix', 'date': '2012-06-10', 'time': '1:32:29.586', 'year': 2012, 'round': 7, 'url_x': 'http://en.wikipedia.org/wiki/2012_Canadian_Grand_Prix'}, {'raceId': 867, 'circuitId': 12.0, 'statusId': 1, 'name_x': 'European Grand Prix', 'date': '2012-06-24', 'time': '+24.653', 'year': 2012, 'round': 8, 'url_x': 'http://en.wikipedia.org/wiki/2012_European_Grand_Prix'}  ... displaying 10 of 232 total bound parameter sets ...  {'raceId': 990, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2018-04-08', 'time': '1:32:01.940', 'year': 2018, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2018_Bahrain_Grand_Prix'}, {'raceId': 951, 'circuitId': 71.0, 'statusId': 1, 'name_x': 'Russian Grand Prix', 'date': '2016-05-01', 'time': '+31.998', 'year': 2016, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2016_Russian_Grand_Prix'})]
(Background on this error at: https://sqlalche.me/e/14/9h9h)
[2024-05-31T13:52:43.650+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T135243, end_date=20240531T135243
[2024-05-31T13:52:43.659+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task load_data__4 ((psycopg2.errors.InvalidDatetimeFormat) invalid input syntax for type time: "+1:19.719"
LINE 1: ...61, 2.0, 1, 'Malaysian Grand Prix', '2012-03-25', '+1:19.719...
                                                             ^

[SQL: INSERT INTO "raceDim" ("raceId", "circuitId", "statusId", name_x, date, time, year, round, url_x) VALUES (%(raceId)s, %(circuitId)s, %(statusId)s, %(name_x)s, %(date)s, %(time)s, %(year)s, %(round)s, %(url_x)s)]
[parameters: ({'raceId': 860, 'circuitId': 1.0, 'statusId': 1, 'name_x': 'Australian Grand Prix', 'date': '2012-03-18', 'time': '1:34:09.565', 'year': 2012, 'round': 1, 'url_x': 'http://en.wikipedia.org/wiki/2012_Australian_Grand_Prix'}, {'raceId': 861, 'circuitId': 2.0, 'statusId': 1, 'name_x': 'Malaysian Grand Prix', 'date': '2012-03-25', 'time': '+1:19.719', 'year': 2012, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2012_Malaysian_Grand_Prix'}, {'raceId': 862, 'circuitId': 17.0, 'statusId': 1, 'name_x': 'Chinese Grand Prix', 'date': '2012-04-15', 'time': '+20.626', 'year': 2012, 'round': 3, 'url_x': 'http://en.wikipedia.org/wiki/2012_Chinese_Grand_Prix'}, {'raceId': 863, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2012-04-22', 'time': '+58.984', 'year': 2012, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2012_Bahrain_Grand_Prix'}, {'raceId': 864, 'circuitId': 4.0, 'statusId': 1, 'name_x': 'Spanish Grand Prix', 'date': '2012-05-13', 'time': '+1:25.246', 'year': 2012, 'round': 5, 'url_x': 'http://en.wikipedia.org/wiki/2012_Spanish_Grand_Prix'}, {'raceId': 865, 'circuitId': 6.0, 'statusId': 1, 'name_x': 'Monaco Grand Prix', 'date': '2012-05-27', 'time': '+4.101', 'year': 2012, 'round': 6, 'url_x': 'http://en.wikipedia.org/wiki/2012_Monaco_Grand_Prix'}, {'raceId': 866, 'circuitId': 7.0, 'statusId': 1, 'name_x': 'Canadian Grand Prix', 'date': '2012-06-10', 'time': '1:32:29.586', 'year': 2012, 'round': 7, 'url_x': 'http://en.wikipedia.org/wiki/2012_Canadian_Grand_Prix'}, {'raceId': 867, 'circuitId': 12.0, 'statusId': 1, 'name_x': 'European Grand Prix', 'date': '2012-06-24', 'time': '+24.653', 'year': 2012, 'round': 8, 'url_x': 'http://en.wikipedia.org/wiki/2012_European_Grand_Prix'}  ... displaying 10 of 232 total bound parameter sets ...  {'raceId': 990, 'circuitId': 3.0, 'statusId': 1, 'name_x': 'Bahrain Grand Prix', 'date': '2018-04-08', 'time': '1:32:01.940', 'year': 2018, 'round': 2, 'url_x': 'http://en.wikipedia.org/wiki/2018_Bahrain_Grand_Prix'}, {'raceId': 951, 'circuitId': 71.0, 'statusId': 1, 'name_x': 'Russian Grand Prix', 'date': '2016-05-01', 'time': '+31.998', 'year': 2016, 'round': 4, 'url_x': 'http://en.wikipedia.org/wiki/2016_Russian_Grand_Prix'})]
(Background on this error at: https://sqlalche.me/e/14/9h9h); 261)
[2024-05-31T13:52:43.676+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-31T13:52:43.687+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-31T13:52:43.692+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T13:59:39.815+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T13:59:39.830+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:59:39.835+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T13:59:39.836+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T13:59:39.844+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T13:59:39.849+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=295) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T13:59:39.850+0000] {standard_task_runner.py:63} INFO - Started process 297 to run task
[2024-05-31T13:59:39.850+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpm4s5chyu']
[2024-05-31T13:59:39.852+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask load_data__4
[2024-05-31T13:59:39.886+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host b6e8a688eec4
[2024-05-31T13:59:39.991+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T13:59:39.992+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T13:59:39.993+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T13:59:39.993+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T13:59:40.014+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T13:59:40.014+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T13:59:40.021+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T135939, end_date=20240531T135940
[2024-05-31T13:59:40.064+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T13:59:40.077+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T13:59:40.078+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T14:10:58.232+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T14:10:58.247+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:10:58.252+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:10:58.253+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T14:10:58.261+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T14:10:58.267+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=286) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T14:10:58.267+0000] {standard_task_runner.py:63} INFO - Started process 288 to run task
[2024-05-31T14:10:58.268+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp6okay1xh']
[2024-05-31T14:10:58.269+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask load_data__4
[2024-05-31T14:10:58.300+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 7fde08b5b7bb
[2024-05-31T14:10:58.397+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T14:10:58.398+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T14:10:58.399+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T14:10:58.399+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T14:10:58.418+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T14:10:58.419+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T14:10:58.426+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T141058, end_date=20240531T141058
[2024-05-31T14:10:58.441+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T14:10:58.454+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T14:10:58.456+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T14:26:10.734+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T14:26:10.750+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:26:10.755+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:26:10.755+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T14:26:10.764+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T14:26:10.770+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=327) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T14:26:10.770+0000] {standard_task_runner.py:63} INFO - Started process 329 to run task
[2024-05-31T14:26:10.771+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp_db1_3rv']
[2024-05-31T14:26:10.773+0000] {standard_task_runner.py:91} INFO - Job 17: Subtask load_data__4
[2024-05-31T14:26:10.806+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host e67b5c96142c
[2024-05-31T14:26:10.908+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T14:26:10.908+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T14:26:10.909+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T14:26:10.910+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T14:26:10.928+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T14:26:10.929+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T14:26:10.935+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T142610, end_date=20240531T142610
[2024-05-31T14:26:10.984+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T14:26:10.998+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T14:26:10.999+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T14:34:42.745+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T14:34:42.761+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:34:42.767+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:34:42.767+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T14:34:42.774+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T14:34:42.780+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=359) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T14:34:42.781+0000] {standard_task_runner.py:63} INFO - Started process 361 to run task
[2024-05-31T14:34:42.782+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmps02k2vyz']
[2024-05-31T14:34:42.783+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask load_data__4
[2024-05-31T14:34:42.818+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host b904eb6286a6
[2024-05-31T14:34:42.925+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T14:34:42.926+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T14:34:42.927+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T14:34:42.927+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T14:34:42.946+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T14:34:42.947+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T14:34:42.954+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T143442, end_date=20240531T143442
[2024-05-31T14:34:42.994+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T14:34:43.008+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-31T14:34:43.010+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T14:41:24.002+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T14:41:24.017+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:41:24.022+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:41:24.022+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T14:41:24.030+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T14:41:24.035+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=384) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T14:41:24.036+0000] {standard_task_runner.py:63} INFO - Started process 386 to run task
[2024-05-31T14:41:24.036+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpw41kqvk4']
[2024-05-31T14:41:24.038+0000] {standard_task_runner.py:91} INFO - Job 20: Subtask load_data__4
[2024-05-31T14:41:24.069+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 39ebc24e8ca6
[2024-05-31T14:41:24.167+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T14:41:24.168+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T14:41:24.169+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T14:41:24.169+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T14:41:24.189+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T14:41:24.189+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T14:41:24.196+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T144124, end_date=20240531T144124
[2024-05-31T14:41:24.209+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T14:41:24.224+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-31T14:41:24.225+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T14:44:44.476+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T14:44:44.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:44:44.496+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:44:44.496+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T14:44:44.504+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T14:44:44.510+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=372) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T14:44:44.511+0000] {standard_task_runner.py:63} INFO - Started process 377 to run task
[2024-05-31T14:44:44.511+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp_is04hal']
[2024-05-31T14:44:44.512+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask load_data__4
[2024-05-31T14:44:44.544+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host a9750641015b
[2024-05-31T14:44:44.644+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T14:44:44.645+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T14:44:44.646+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T14:44:44.646+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T14:44:44.666+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T14:44:44.666+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T14:44:44.673+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T144444, end_date=20240531T144444
[2024-05-31T14:44:44.724+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T14:44:44.738+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-31T14:44:44.740+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-31T14:48:50.180+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-31T14:48:50.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:48:50.200+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [queued]>
[2024-05-31T14:48:50.200+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-31T14:48:50.208+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_data__4> on 2024-05-30 00:00:00+00:00
[2024-05-31T14:48:50.213+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=383) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-31T14:48:50.214+0000] {standard_task_runner.py:63} INFO - Started process 385 to run task
[2024-05-31T14:48:50.214+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'f1_data_pipeline_taskflow', 'load_data__4', 'scheduled__2024-05-30T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp0vjpeq_c']
[2024-05-31T14:48:50.216+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask load_data__4
[2024-05-31T14:48:50.250+0000] {task_command.py:426} INFO - Running <TaskInstance: f1_data_pipeline_taskflow.load_data__4 scheduled__2024-05-30T00:00:00+00:00 [running]> on host 5e099e29bc21
[2024-05-31T14:48:50.352+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='f1_data_pipeline_taskflow' AIRFLOW_CTX_TASK_ID='load_data__4' AIRFLOW_CTX_EXECUTION_DATE='2024-05-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-30T00:00:00+00:00'
[2024-05-31T14:48:50.353+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-31T14:48:50.354+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-05-31T14:48:50.354+0000] {base.py:84} INFO - Using connection ID 'sourcedb_connection' for task execution.
[2024-05-31T14:48:50.374+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-31T14:48:50.374+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-31T14:48:50.381+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=f1_data_pipeline_taskflow, task_id=load_data__4, run_id=scheduled__2024-05-30T00:00:00+00:00, execution_date=20240530T000000, start_date=20240531T144850, end_date=20240531T144850
[2024-05-31T14:48:50.427+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-31T14:48:50.442+0000] {taskinstance.py:3498} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2024-05-31T14:48:50.444+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
