[2024-06-18T09:27:22.161+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: f1_data_pipeline_kafka_fetchAndPublish.fetch_and_publish_raceResults manual__2024-06-18T09:27:20.128872+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
